/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import adt.LinkedList;
import adt.Node;
import data.Client;
import data.Dish;
import data.Order;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import logic.MyFile;

/**
 *
 * @author carov
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    //Model para Cada Lista (Entradas, Plato Fuerte, Bebidas, Postre)
    DefaultListModel modelentr = new DefaultListModel();
    DefaultListModel modelpf = new DefaultListModel();
    DefaultListModel modelbeb = new DefaultListModel();
    DefaultListModel modelpos = new DefaultListModel();

    //Manejo de Archivos
    MyFile f = new MyFile();

    //Guardar en lista todos los platos
    LinkedList<Dish> dishes = f.readDishes();

    //Lista para guardar cada plato ordenado por el cliente
    LinkedList<Dish> orderDish = new LinkedList<Dish>();
    
    //Variable para guardar al cliente obtenido ya sea del registro o del login
    private Client c;

    public MenuGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        fillMenu(dishes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_entradas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_platofuerte = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_bebidas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_postres = new javax.swing.JList<>();
        button_otropedido = new javax.swing.JButton();
        button_terminarpedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 243, 224));

        list_entradas.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        list_entradas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(list_entradas);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 76, 65));
        jLabel1.setText("Te damos la bienvenida");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 76, 65));
        jLabel2.setText("Menu Disponible:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/imgindex64.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(109, 76, 65));
        jLabel4.setText("Platos fuertes");

        label_username.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        label_username.setForeground(new java.awt.Color(230, 74, 25));
        label_username.setText("correo@correo.com");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(109, 76, 65));
        jLabel6.setText("Entradas");

        list_platofuerte.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        list_platofuerte.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(list_platofuerte);

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(109, 76, 65));
        jLabel7.setText("bebidas");

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(109, 76, 65));
        jLabel8.setText("postres");

        list_bebidas.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        list_bebidas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(list_bebidas);

        list_postres.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        list_postres.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(list_postres);

        button_otropedido.setBackground(new java.awt.Color(109, 76, 65));
        button_otropedido.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        button_otropedido.setForeground(new java.awt.Color(255, 243, 224));
        button_otropedido.setText("Agregar al carrito");
        button_otropedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_otropedidoActionPerformed(evt);
            }
        });

        button_terminarpedido.setBackground(new java.awt.Color(109, 76, 65));
        button_terminarpedido.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        button_terminarpedido.setForeground(new java.awt.Color(255, 243, 224));
        button_terminarpedido.setText("Terminar Pedidos");
        button_terminarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_terminarpedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(302, 302, 302))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_username))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_otropedido)
                        .addGap(18, 18, 18)
                        .addComponent(button_terminarpedido)
                        .addGap(130, 130, 130)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_username)
                    .addComponent(jLabel1))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_otropedido)
                    .addComponent(button_terminarpedido))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_otropedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_otropedidoActionPerformed
        // TODO add your handling code here:

        Dish dentrada, dpfuerte, dbebida, dpostre;

        try {
            dentrada = (Dish) modelentr.getElementAt(list_entradas.getSelectedIndex());
            dpfuerte = (Dish) modelpf.getElementAt(list_platofuerte.getSelectedIndex());
            dbebida = (Dish) modelbeb.getElementAt(list_bebidas.getSelectedIndex());
            dpostre = (Dish) modelpos.getElementAt(list_postres.getSelectedIndex());
            orderDish.pushBack(dentrada);
            orderDish.pushBack(dpfuerte);
            orderDish.pushBack(dbebida);
            orderDish.pushBack(dpostre);

            JOptionPane.showMessageDialog(rootPane, "Pedido Agregado al carrito!", "Informacion Carrito", JOptionPane.INFORMATION_MESSAGE);

            list_entradas.clearSelection();
            list_platofuerte.clearSelection();
            list_bebidas.clearSelection();
            list_postres.clearSelection();

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Porfavor selecciona algo en cada tipo de plato!", "Error al agregar al carrito", JOptionPane.OK_OPTION);
        }


    }//GEN-LAST:event_button_otropedidoActionPerformed

    private void button_terminarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_terminarpedidoActionPerformed
        // TODO add your handling code here:
        try {
            if (orderDish.isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Aun no has hecho nigun pedido!", "Error al completar el pedido", JOptionPane.OK_OPTION);
                
            } else {
          
                OrderConfirmationGUI ocg = new OrderConfirmationGUI();
                
                //Se crea la orden
                Order ord = new Order(orderDish, this.c );
                this.dispose();
                ocg.setVisible(true);
                ocg.loadOrder(ord);
            }

            clearLists();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_button_terminarpedidoActionPerformed

    public void setUserName(Client c) {
        this.c = c;
        label_username.setText(c.getEmail());
    }


    public void fillMenu(LinkedList<Dish> dishes) {

        Dish tempdish;
        String type;

        modelentr.addElement(new Dish("Sin Entrada"));
        modelpf.addElement(new Dish("Sin Plato Fuerte"));
        modelbeb.addElement(new Dish("Sin bebida"));
        modelpos.addElement(new Dish("Sin Postre"));

        if (dishes != null) {
            Node temp = dishes.getHead();
            while (temp != null) {
                tempdish = (Dish) temp.data;
                type = tempdish.getType();
                if (type.equals("Entrada")) {
                    modelentr.addElement(tempdish);
                } else if (type.equals("Plato Fuerte")) {
                    modelpf.addElement(tempdish);
                } else if (type.equals("Bebida")) {
                    modelbeb.addElement(tempdish);
                } else if (type.equals("Postres")) {
                    modelpos.addElement(tempdish);
                }
                temp = temp.next;
            }
        }
        
        list_entradas.setModel(modelentr);
        list_platofuerte.setModel(modelpf);
        list_bebidas.setModel(modelbeb);
        list_postres.setModel(modelpos);

    }
    
    public void clearLists() {
        list_entradas.clearSelection();
        list_platofuerte.clearSelection();
        list_bebidas.clearSelection();
        list_postres.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_otropedido;
    private javax.swing.JButton button_terminarpedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_username;
    private javax.swing.JList<String> list_bebidas;
    private javax.swing.JList<String> list_entradas;
    private javax.swing.JList<String> list_platofuerte;
    private javax.swing.JList<String> list_postres;
    // End of variables declaration//GEN-END:variables


}
